site_name: URL to QR Code
site_url: https://glenpetrovich.github.io/url-to-qr-code/
theme:
  name: material
site_author: Glen Petrovich
copyright: Glen Petrovich, 2024
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      toc_depth: 0